PREFIX dct: <http://purl.org/dc/terms/>
PREFIX msc: <http://msc2010.org/resources/MSC/2010/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?decade (COUNT(DISTINCT ?pub) AS ?count)
FROM <https://zbmath.org>
WHERE {
  ?pub a <https://schema.org/ScholarlyArticle> ;
       dct:issued ?year .

  BIND(FLOOR(xsd:integer(STR(?year))/10)*10 AS ?decade)
}
GROUP BY ?decade
ORDER BY ?decade
