#narrative of intellectual influence.
PREFIX schema:   <https://schema.org/>
PREFIX dcterms:  <http://purl.org/dc/terms/>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT
    ?reviewedTitle
    ?reviewedYear
    ?reviewedMSC
    ?authoredTitle
    ?authoredYear
    ?authoredMSC
    ?keywordLabel

WHERE {

    # Hans L. Bodlaender reviews
    ?review a schema:Review ;
            schema:reviewer <https://zbmath.org/authors/bodlaender.hans-l> ;
            schema:itemReviewed ?reviewedPaper .

    ?reviewedPaper
        dcterms:issued ?reviewedYear ;
        schema:name ?reviewedTitle ;
        dcterms:subject ?reviewedMSC ;
        schema:keywords ?keyword .

    FILTER(YEAR(?reviewedYear) <= 2000)

    # Hans L. Bodlaender authored papers
    ?authoredPaper
        schema:author <https://zbmath.org/authors/bodlaender.hans-l> ;
        dcterms:issued ?authoredYear ;
        schema:name ?authoredTitle ;
        dcterms:subject ?authoredMSC ;
        schema:keywords ?keyword .

    FILTER(YEAR(?authoredYear) >= 2000)
    FILTER(YEAR(?authoredYear) <= 2025)

    ?keyword skos:prefLabel ?keywordLabel .

    FILTER(?reviewedPaper != ?authoredPaper)
}
ORDER BY ?reviewedYear ?authoredYear ?keywordLabel

# PREFIX schema: <https://schema.org/>
# PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

# SELECT DISTINCT
#     ?reviewedPaperTitle
#     ?authoredPaperTitle
#     ?keywordLabel

# WHERE {

#     # Reviews written by Salvatore Sessa
#     ?review a schema:Review ;
#             schema:reviewer <https://zbmath.org/authors/sessa.salvatore> ;
#             schema:itemReviewed ?reviewedPaper .

#     ?reviewedPaper
#         schema:name ?reviewedPaperTitle ;
#         schema:keywords ?keyword .

#     # Papers authored by the same person
#     ?authoredPaper
#         schema:author <https://zbmath.org/authors/sessa.salvatore> ;
#         schema:name ?authoredPaperTitle ;
#         schema:keywords ?keyword .

#     ?keyword skos:prefLabel ?keywordLabel .

#     # Avoid matching the same paper if applicable
#     FILTER(?reviewedPaper != ?authoredPaper)

# }
# ORDER BY ?keywordLabel ?reviewedPaperTitle ?authoredPaperTitle

